# Generated by Django 5.1.2 on 2024-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='number_of_references',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
