# Generated by Django 5.1.2 on 2024-11-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reference_number_of_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='number_of_references',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
