# Generated by Django 5.1.2 on 2024-11-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_profile', 'Can view profile'), ('can_edit_profile', 'Can edit profile'), ('can_delete_profile', 'Can delete profile'), ('can_create_profile', 'Can create profile'), ('can_list_profile', 'Can list profile'), ('can_search_profile', 'Can search profile'), ('can_export_profile', 'Can export profile'), ('can_import_profile', 'Can import profile'), ('can_send_profile', 'Can send profile')], 'verbose_name': 'Profile'},
        ),
    ]
